### ISSUE TITLE
Error in curl::curl_fetch_memory when Drupal two pages sitemap.

### ISSUE THREAD

**Issue by peterisj** [pixgarden/xsitemap#5]
When your site have more then 2000 links, Drupal start separate sitemap in two pages.

Examples:
https://www.tm.gov.lv/sitemap.xml
https://www.sam.gov.lv/sitemap.xml

xsitemap get correct second url "http://www.tm.gov.lv/sitemap.xml?page=1" , but not get content. Show error 
```1 >>> http://www.tm.gov.lv/sitemap.xml?page=1
Reaching for XML sitemap... http://www.tm.gov.lv/sitemap.xml?page=1
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer
```

**Comment by fljoly** [comment]
can't reproduce the problem.

`sitemap_urls <- xsitemapGet("https://www.tm.gov.lv/")`
`sitemap_urls <- xsitemapGet("https://www.sam.gov.lv/sitemap.xml")`

Both seem to work well for me. It's probably a `curl` or `httr`  package issue, please try to update
